// Generated by nuxt-simple-sitemap

declare module 'nitropack' {
  interface NitroRouteRules {
    index?: boolean
    sitemap?: import('../../../node_modules/.pnpm/nuxt-simple-sitemap@4.4.1_@nuxt+devtools@1.3.9_rollup@4.18.0_vite@5.3.3_@types+node@20.14.10__q7ffote3zbhg7sxgcje4ik2bjm/node_modules/nuxt-simple-sitemap/dist/runtime/types').SitemapItemDefaults
  }
  interface NitroRouteConfig {
    index?: boolean
    sitemap?: import('../../../node_modules/.pnpm/nuxt-simple-sitemap@4.4.1_@nuxt+devtools@1.3.9_rollup@4.18.0_vite@5.3.3_@types+node@20.14.10__q7ffote3zbhg7sxgcje4ik2bjm/node_modules/nuxt-simple-sitemap/dist/runtime/types').SitemapItemDefaults
  }
  interface NitroRuntimeHooks {
    'sitemap:resolved': (ctx: import('../../../node_modules/.pnpm/nuxt-simple-sitemap@4.4.1_@nuxt+devtools@1.3.9_rollup@4.18.0_vite@5.3.3_@types+node@20.14.10__q7ffote3zbhg7sxgcje4ik2bjm/node_modules/nuxt-simple-sitemap/dist/runtime/types').SitemapRenderCtx) => void | Promise<void>
    'sitemap:output': (ctx: import('../../../node_modules/.pnpm/nuxt-simple-sitemap@4.4.1_@nuxt+devtools@1.3.9_rollup@4.18.0_vite@5.3.3_@types+node@20.14.10__q7ffote3zbhg7sxgcje4ik2bjm/node_modules/nuxt-simple-sitemap/dist/runtime/types').SitemapOutputHookCtx) => void | Promise<void>
  }
}
declare module 'vue-router' {
    interface RouteMeta {
        sitemap?: import('../../../node_modules/.pnpm/nuxt-simple-sitemap@4.4.1_@nuxt+devtools@1.3.9_rollup@4.18.0_vite@5.3.3_@types+node@20.14.10__q7ffote3zbhg7sxgcje4ik2bjm/node_modules/nuxt-simple-sitemap/dist/runtime/types').SitemapItemDefaults
    }
}

export {}
