// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/nuxt@3.12.3_@parcel+watcher@2.4.1_@types+node@20.14.10_eslint@9.6.0_ioredis@5.4.1_magicast@0._zbg4noxekcn2dah5lk5lam6gna/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/sitemap_index.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/nuxt-simple-sitemap@4.4.1_@nuxt+devtools@1.3.9_rollup@4.18.0_vite@5.3.3_@types+node@20.14.10__q7ffote3zbhg7sxgcje4ik2bjm/node_modules/nuxt-simple-sitemap/dist/runtime/routes/sitemap_index.xml').default>>>>
    }
    '/en-sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/nuxt-simple-sitemap@4.4.1_@nuxt+devtools@1.3.9_rollup@4.18.0_vite@5.3.3_@types+node@20.14.10__q7ffote3zbhg7sxgcje4ik2bjm/node_modules/nuxt-simple-sitemap/dist/runtime/middleware/[sitemap]-sitemap.xml').default>>>>
    }
    '/sp-sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/nuxt-simple-sitemap@4.4.1_@nuxt+devtools@1.3.9_rollup@4.18.0_vite@5.3.3_@types+node@20.14.10__q7ffote3zbhg7sxgcje4ik2bjm/node_modules/nuxt-simple-sitemap/dist/runtime/middleware/[sitemap]-sitemap.xml').default>>>>
    }
    '/zh-cn-sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/nuxt-simple-sitemap@4.4.1_@nuxt+devtools@1.3.9_rollup@4.18.0_vite@5.3.3_@types+node@20.14.10__q7ffote3zbhg7sxgcje4ik2bjm/node_modules/nuxt-simple-sitemap/dist/runtime/middleware/[sitemap]-sitemap.xml').default>>>>
    }
    '/__sitemap__/style.xsl': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/nuxt-simple-sitemap@4.4.1_@nuxt+devtools@1.3.9_rollup@4.18.0_vite@5.3.3_@types+node@20.14.10__q7ffote3zbhg7sxgcje4ik2bjm/node_modules/nuxt-simple-sitemap/dist/runtime/routes/sitemap.xsl').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/nuxt-simple-sitemap@4.4.1_@nuxt+devtools@1.3.9_rollup@4.18.0_vite@5.3.3_@types+node@20.14.10__q7ffote3zbhg7sxgcje4ik2bjm/node_modules/nuxt-simple-sitemap/dist/runtime/routes/sitemap.xml').default>>>>
    }
  }
}
export {}